### ISSUE TITLE
Registration Flow for newly registering user

### ISSUE THREAD

**Issue by ritheon** [rudkodm/closer-ui#8]
1. Newly registering user should not be able to log in to the system until he's verified his email.
2. After providing business details screen should be reloaded and user should be brought to the tab currently called "Info" where he'll see provided business details.
3. Merchant should not be able to create promotions until he's completed the registration flow and provided all business details (Name, Category, Register Name, Register Surname etc.):
   - after login the system should check whether the business details are provided
   - if not, merchant should not be able to move from "Info" page before he will complete all required information.  
   - submit button should be blocked if not all information is provided or invalid.
   - not valid fields should be highlighted red with clarification messages.
   - if user will try to manually switch to forbidden page - he will be redirected to 'error' page where error information will be shown. 
   - On error page there should be "Back" button - to move back to a previous step 
4. User should be able to update business details but the system should not let him update them if some of the fields where made blank (validation on Save button click).

**Comment by rudkodm** [comment]
> Newly registering user should not be able to log in to the system until he's verified his email.

Implementation details: https://github.com/rudkodm/closer-ui/issues/6#issuecomment-256331058
